name: Build and Deploy Backend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install
        working-directory: ./backend

      - name: Ejecutar pruebas
        run: npm test || echo "sin pruebas"
        working-directory: ./backend

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Llamar API de Render para deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
